version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 99
  reviewers:
  - varunsridharan
  assignees:
  - varunsridharan
  ignore:
  - dependency-name: elliptic
    versions:
    - 6.5.3
